### ISSUE TITLE
themer row fallback image not working (pods extended field)

### ISSUE THREAD

**Issue by Masti81** [pods-framework/pods-beaver-builder-themer-add-on#100]
Hello,

https://github.com/pods-framework/pods-beaver-builder-themer-add-on/issues/67

I think an issue related to the above closed issue is occurring for me . Although instead of on a photo module it is a themer part row image.

The rows image field is connecting to a PODS extended page field. If this field is left
null then a default fallback
 image is set to apply instead.
-The default image will display for "pages", the problem we have is that for "products" and "posts", if this field is null then it will just
ignore the fallback image and will just have a grey background.

POD: page(post type - extended) > Field: header_image

BB THEMER: http://shedcraft.ascet.co/fl-theme-layout/page-title-with-image-and-slogan/?fl_builder
a page: http://shedcraft.ascet.co/online-shop/
a product: http://shedcraft.ascet.co/product/jungle-fort-stained-ex-display/
a post: http://shedcraft.ascet.co/things-to-consider-when-installing-a-garden-shed/

Beaver Builder Plugin (Pro Version) Version 2.2.2.6
Beaver Themer Version 1.2.3.4
Pods - Custom Content Types and Fields Version 2.7.12
Pods Beaver Themer Add-On Version 1.3.2

Please can you assist with this again?

[pods export.txt](https://github.com/pods-framework/pods-beaver-builder-themer-add-on/files/3182156/pods.export.txt)

**Comment by quasel** [comment]
Hi, to try to recreate the issue you did create a themer part and assigned it to all locations and then you set the image to be pulled from a extended page field - the issues might be that posts/products are not a page - easiest workaround would be just create on part for pages and a different one for posts/products as they don't need the overhead of the logic and just set a single image there…

**Comment by quasel** [comment]
Been a long time - going to close that - if you still have issues feel free to comment!
