### ISSUE TITLE
Javascript error on HTTP request; Can't save an update

### ISSUE THREAD

**Issue by sherrigoodman** [pods-framework/pods-beaver-builder-themer-add-on#101]
**Issue Overview**
I'm working on a local environ using Flywheel on my laptop (Macbook Pro 2017 using MacOS Mojave 10.14.5) and using Beaver Builder Pro, Beaver Themer, Pods, Pods Beaver Themer Addon, plus UABB, BBVapor, and PowerPack modules. 

I was able to work with everything up to 2-3 days ago when I started experiencing a problem with saving an update while working with a Posts module - bringing in a CPT created in Pods through the content tab in the module. Right after selecting the CPT I get an error message like the screenshot attached:

[Pods-BeaverThemeAdd-on_Javascript-issue.txt](https://github.com/pods-framework/pods-beaver-builder-themer-add-on/files/3267944/Pods-BeaverThemeAdd-on_Javascript-issue.txt)
![Screen Shot 2019-06-07 at 4 37 39 PM](https://user-images.githubusercontent.com/49343745/59139723-cf986600-8949-11e9-9410-49010b8cd7dd.png)

**Expected Behavior**
I was expecting to continue with my edits and complete setting up my preferences for the Posts module and saving it.

**Current Behavior**
I get the error message about a possible javascript issue when I try to select my options in the module. The error message comes up even before I try to click to save the module. Here's the text from Chrome's Javascript Console:

JQMIGRATE: Migrate is installed, version 1.4.1
jquery.js?ver=1.12.4-wp:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?ver=1.12.4-wp:4
fl-builder.min.js:6 ************************************************************************
fl-builder.min.js:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js:6 TypeError: Cannot read property 'data' of undefined
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:100:117)
    at HTMLDocument.<anonymous> (fl-builder.min.js:2)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at Object.n.fn.ready [as oldReady] (jquery.js:2)
    at n.fn.init.FLBuilderConfig.debug.jQuery.fn.ready (fl-builder.min.js:2)
    at a.fn.init.n.fn.init (jquery.js:2)
    at new a.fn.init (jquery-migrate.min.js:2)
    at n (jquery.js:2)
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:97:169)
fl-builder.min.js:6 ************************************************************************

 
**Possible Solution**
I don't know. It has something to do with a non-HTTPS version of javascript being called in. The only reason I think this is because of previous attempts to resolve this:

Note: The site owner has disabled Google Analytics tracking for your user role.
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
?fl_builder:1 **Mixed Content: The page at 'https://mcdill-associates.local/about/?fl_builder' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jquery.cycle/2.99/jquery.cycle.all.min.js?ver=2.99'. This request has been blocked; the content must be served over HTTPS.**
jquery.js?ver=1.12.4-wp:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?ver=1.12.4-wp:4
fl-builder.min.js:6 ************************************************************************
fl-builder.min.js:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js:6 TypeError: Cannot read property 'data' of undefined
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:176:117)
    at HTMLDocument.<anonymous> (fl-builder.min.js:2)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at Object.n.fn.ready [as oldReady] (jquery.js:2)
    at n.fn.init.FLBuilderConfig.debug.jQuery.fn.ready (fl-builder.min.js:2)
    at a.fn.init.n.fn.init (jquery.js:2)
    at new a.fn.init (jquery-migrate.min.js:2)
    at n (jquery.js:2)
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:173:169)
fl-builder.min.js:6 ************************************************************************
2/wp-admin/admin-ajax.php:1 Failed to load resource: net::ERR_NETWORK_CHANGED

**Steps to Reproduce (for bugs)**
1. Drag in the Posts module into a page layout (nothing special about the page set up - just the usual default Beaver Builder Pro plugin). 
2. In the Layout tab, select Layout: Columns.
3. In the Content tab, Post Type: select CPT from list (in my list is "Our Team").
4. Error message pops up after a 1-2 second delay.

**Steps Taken to Resolve (Unsuccessfully)**
1. Put in a support ticket with Beaver Builder explaining my issue (as described above).
2. Feedback was to switch all database references of HTTP:// to HTTPS:// ---> which I did.
3. Went back to the page I was trying to add CPT on (the About Us page) and tried to edit the Posts module again. And had the same result. 
4. Got the Javascript Console bug report and sent that along to the Beaver Builder Support. Noticed the note about testing for plugin conflict.
5. I turned off all plugins except for Beaver Builder Pro, Beaver Themer, Pods, and Pods Beaver Themer Addon. 
6. Went through the same actions as in (3) above... same result.
7. I then deactivated Pods Beaver Themer Addon and went through the same actions as in (3) above. Had a successful attempt at setting any and all options in the module and saved it. No error message this time. 
8. I activated Pods Beaver Themer Addon again and tried the same actions as in (3) above - and it gave me another error message and was unable to save the module. 
9. I deactivated Pods Beaver Themer Addon once more, pulled in a fresh Posts module to the page and started to set it up - and was able to make the settings again and I could save the module successfully.

**Pods Package Export (helpful!)**
Could not paste the text into the box provided in the previous section above in this form, so I attached a text file of the same.

**Wordpress Environment:**
Aside from running this install on Local by Flywheel on my laptop, I'm running all the latest versions of everything. Here's the list:
Debug Information
WordPress Version: 5.2.1

PHP Version: 7.2.9

MySQL Version: 5.7.23

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: supermcdillwp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 19.852M

Current Memory Usage (real): 6.000M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:

Akismet Anti-Spam: 4.1.2
Autoptimize: 2.5.1
BackupBuddy: 8.4.15.0
BB Vapor Modules Pro: 1.0.13
Beaver Builder Plugin (Pro Version): 2.2.3
Beaver Themer: 1.2.3.4
Code Studio: 1.1.5
Disable Gutenberg: 1.8.1
Google Analytics for WordPress by MonsterInsights: 7.6.0
Google Apps Login: 3.2
Google Drive Embedder: 5.1
Gravity Forms: 2.4.9
Gravity Forms MailChimp Add-On: 4.6
iThemes Security: 7.3.3
iThemes Sync: 2.0.15
Pods - Custom Content Types and Fields: 2.7.12
PowerPack for Beaver Builder: 2.7.0.2
Redirection: 4.3
Smush Pro: 3.2.1
Testimonials by Solamar: 1.2.1.1
Ultimate Addons for Beaver Builder: 1.17.1
WordPress Importer: 0.6.4
WP All Export: 1.2.3
WPMU DEV Dashboard: 4.7.1.2
Yoast SEO: 11.3

Let me know if you want any other info. I was planning to migrate this site up to a live hosting environment soon and see if things change by doing that. Not sure if maybe the Local environment may be causing an issue.

:-)

**Comment by sherrigoodman** [comment]
**Issue Overview**
I'm working on a local environ using Flywheel on my laptop (Macbook Pro 2017 using MacOS Mojave 10.14.5) and using Beaver Builder Pro, Beaver Themer, Pods, Pods Beaver Themer Addon, plus UABB, BBVapor, and PowerPack modules. 

I was able to work with everything up to 2-3 days ago when I started experiencing a problem with saving an update while working with a Posts module - bringing in a CPT created in Pods through the content tab in the module. Right after selecting the CPT I get an error message like the screenshot attached:

[Pods-BeaverThemeAdd-on_Javascript-issue.txt](https://github.com/pods-framework/pods-beaver-builder-themer-add-on/files/3267944/Pods-BeaverThemeAdd-on_Javascript-issue.txt)
![Screen Shot 2019-06-07 at 4 37 39 PM](https://user-images.githubusercontent.com/49343745/59139723-cf986600-8949-11e9-9410-49010b8cd7dd.png)

**Expected Behavior**
I was expecting to continue with my edits and complete setting up my preferences for the Posts module and saving it.

**Current Behavior**
I get the error message about a possible javascript issue when I try to select my options in the module. The error message comes up even before I try to click to save the module. Here's the text from Chrome's Javascript Console:

JQMIGRATE: Migrate is installed, version 1.4.1
jquery.js?ver=1.12.4-wp:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?ver=1.12.4-wp:4
fl-builder.min.js:6 ************************************************************************
fl-builder.min.js:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js:6 TypeError: Cannot read property 'data' of undefined
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:100:117)
    at HTMLDocument.<anonymous> (fl-builder.min.js:2)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at Object.n.fn.ready [as oldReady] (jquery.js:2)
    at n.fn.init.FLBuilderConfig.debug.jQuery.fn.ready (fl-builder.min.js:2)
    at a.fn.init.n.fn.init (jquery.js:2)
    at new a.fn.init (jquery-migrate.min.js:2)
    at n (jquery.js:2)
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:97:169)
fl-builder.min.js:6 ************************************************************************

 
**Possible Solution**
I don't know. It has something to do with a non-HTTPS version of javascript being called in. The only reason I think this is because of previous attempts to resolve this:

Note: The site owner has disabled Google Analytics tracking for your user role.
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
?fl_builder:1 **Mixed Content: The page at 'https://mcdill-associates.local/about/?fl_builder' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jquery.cycle/2.99/jquery.cycle.all.min.js?ver=2.99'. This request has been blocked; the content must be served over HTTPS.**
jquery.js?ver=1.12.4-wp:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?ver=1.12.4-wp:4
fl-builder.min.js:6 ************************************************************************
fl-builder.min.js:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js:6 TypeError: Cannot read property 'data' of undefined
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:176:117)
    at HTMLDocument.<anonymous> (fl-builder.min.js:2)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at Object.n.fn.ready [as oldReady] (jquery.js:2)
    at n.fn.init.FLBuilderConfig.debug.jQuery.fn.ready (fl-builder.min.js:2)
    at a.fn.init.n.fn.init (jquery.js:2)
    at new a.fn.init (jquery-migrate.min.js:2)
    at n (jquery.js:2)
    at eval (eval at <anonymous> (jquery.js:2), <anonymous>:173:169)
fl-builder.min.js:6 ************************************************************************
2/wp-admin/admin-ajax.php:1 Failed to load resource: net::ERR_NETWORK_CHANGED

**Steps to Reproduce (for bugs)**
1. Drag in the Posts module into a page layout (nothing special about the page set up - just the usual default Beaver Builder Pro plugin). 
2. In the Layout tab, select Layout: Columns.
3. In the Content tab, Post Type: select CPT from list (in my list is "Our Team").
4. Error message pops up after a 1-2 second delay.

**Steps Taken to Resolve (Unsuccessfully)**
1. Put in a support ticket with Beaver Builder explaining my issue (as described above).
2. Feedback was to switch all database references of HTTP:// to HTTPS:// ---> which I did.
3. Went back to the page I was trying to add CPT on (the About Us page) and tried to edit the Posts module again. And had the same result. 
4. Got the Javascript Console bug report and sent that along to the Beaver Builder Support. Noticed the note about testing for plugin conflict.
5. I turned off all plugins except for Beaver Builder Pro, Beaver Themer, Pods, and Pods Beaver Themer Addon. 
6. Went through the same actions as in (3) above... same result.
7. I then deactivated Pods Beaver Themer Addon and went through the same actions as in (3) above. Had a successful attempt at setting any and all options in the module and saved it. No error message this time. 
8. I activated Pods Beaver Themer Addon again and tried the same actions as in (3) above - and it gave me another error message and was unable to save the module. 
9. I deactivated Pods Beaver Themer Addon once more, pulled in a fresh Posts module to the page and started to set it up - and the error message resulted again.

**Pods Package Export (helpful!)**
Could not paste the text into the box provided in the previous section above in this form, so I attached a text file of the same.

**Wordpress Environment:**
Aside from running this install on Local by Flywheel on my laptop, I'm running all the latest versions of everything. Here's the list:
Debug Information
WordPress Version: 5.2.1

PHP Version: 7.2.9

MySQL Version: 5.7.23

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: supermcdillwp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 19.852M

Current Memory Usage (real): 6.000M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:

Akismet Anti-Spam: 4.1.2
Autoptimize: 2.5.1
BackupBuddy: 8.4.15.0
BB Vapor Modules Pro: 1.0.13
Beaver Builder Plugin (Pro Version): 2.2.3
Beaver Themer: 1.2.3.4
Code Studio: 1.1.5
Disable Gutenberg: 1.8.1
Google Analytics for WordPress by MonsterInsights: 7.6.0
Google Apps Login: 3.2
Google Drive Embedder: 5.1
Gravity Forms: 2.4.9
Gravity Forms MailChimp Add-On: 4.6
iThemes Security: 7.3.3
iThemes Sync: 2.0.15
Pods - Custom Content Types and Fields: 2.7.12
PowerPack for Beaver Builder: 2.7.0.2
Redirection: 4.3
Smush Pro: 3.2.1
Testimonials by Solamar: 1.2.1.1
Ultimate Addons for Beaver Builder: 1.17.1
WordPress Importer: 0.6.4
WP All Export: 1.2.3
WPMU DEV Dashboard: 4.7.1.2
Yoast SEO: 11.3

Let me know if you want any other info. I was planning to migrate this site up to a live hosting environment soon and see if things change by doing that. Not sure if maybe the Local environment may be causing an issue.

:-)

**Comment by nicdford** [comment]
Hey @quasel I was able to reproduce this as well. I'll try and do a bit of digging and see if I can't figure it out.

**Comment by quasel** [comment]
Oups sorry missed that one - will try to take a look this week - it's just soooo hot dam :/

**Comment by nicdford** [comment]
Hi @sherrigoodman, still digging, but I did find if you rollback bb-plugin to version 2.2.1.5, that should restore functionality. Hopefully @quasel or I can find a fix, but for the time being, hopefully that gets your site running.

**Comment by sherrigoodman** [comment]
Great, thanks so much! :-D


---- On Fri, 28 Jun 2019 14:55:55 -0700 Nic Ford <notifications@github.com> wrote ----


Hi https://github.com/sherrigoodman, still digging, but I did find if you rollback bb-plugin to version 2.2.1.5, that should restore functionality. Hopefully https://github.com/quasel or I can find a fix, but for the time being, hopefully that gets your site running.
