### ISSUE TITLE
Author Archive: unable to pull in added User photo field in a row background

### ISSUE THREAD

**Issue by codente** [pods-framework/pods-beaver-builder-themer-add-on#106]
## Issue Overview
It seems like this is no longer working to pull in a User field into the row background

## Expected Behavior
Would expect that it works

## Current Behavior
The image does not get pulled in.

## Steps to Reproduce (for bugs)
1.  Extend users and add a photo field.
2. Add a photo to that field for  at least one user
3. Create an author archive in Themer using the default template.
4. Try to connect that user photo field to the row background.
5.  The image does not display when viewing that Author's archive.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by quasel** [comment]
I'll look into it - weird thing

**Comment by jimtrue** [comment]
Was it a Gravatar field? Or can it use a Gravatar field?

**Comment by quasel** [comment]
No it was an extended User - it works in a post module but not for Author Archives…

**Comment by quasel** [comment]
finally got around to take a lock - totally slipped my mind - improved user handling! - please test https://github.com/pods-framework/pods-beaver-builder-themer-add-on/tree/release/1.3.6

**Comment by quasel** [comment]
Btw This fixes a lot more issues around displaying user data!
