### ISSUE TITLE
Doesn't Work with Arabic WordPress Installation

### ISSUE THREAD

**Issue by muh3000** [pods-framework/pods-beaver-builder-themer-add-on#107]
## Issue Overview
It work just fine with English Wordpress installation but I have installed this plugin in my Arabic Wordpress and created these issues:

- it showed this message "Pods Beaver Themer requires that the Pods and Beaver Builder Themer plugins be installed and activated." at the top
- cannot manage the media
- cannot search for new plugins

So, I had to deactivate the plugin and started to work normal.

Do you have work around?

WordPress 5.4.2
Pods Beaver Themer Add-On 1.3.3

Regards,

Mohammad Alnasser

**Comment by quasel** [comment]
Hi, sorry for the late reply - do you still have that issue?

**Comment by muh3000** [comment]
Hi,

I have removed it since that time. Please let me know if you made a fix
already.

Regards,

**Comment by quasel** [comment]
I never could replicate the issues you described - I'm going to close the issue - if you test it feel free to report back!
