### ISSUE TITLE
Missing Field Connections Options When More Then 1 Relationship

### ISSUE THREAD

**Issue by reachadam** [pods-framework/pods-beaver-builder-themer-add-on#36]
Having a weird issue with how I am using PODS Beaver Themer integration. In this CPT I have 2 relationships to another CPT. Both go to the same CPT but it is done this way to give me control of the related fields and how I want to lay it out in Beaver Themer. My issue is I can only choose fields from 1 of the relationships, not both.
<img width="599" alt="screenshot 2017-06-19 16 24 43" src="https://user-images.githubusercontent.com/20959226/27344913-dd2ea654-559c-11e7-873d-04249af4a5bc.png">

**Comment by quasel** [comment]
Task: Try to improve the recursive function - currently to prevent loops it only visits each CPT once! 

Workaround: use the manual connection e.g
Images:
![pasted image at 2017_06_20 19_47](https://user-images.githubusercontent.com/9464217/27347659-9d3ba1be-55f1-11e7-905c-8d5b612a52b7.png)
Text, Url, String:
![ohne titel 4](https://user-images.githubusercontent.com/9464217/27347720-d9e9f264-55f1-11e7-8be2-75e588e9ec80.png)

**Comment by quasel** [comment]
Solved with https://github.com/pods-framework/pods-beaver-builder-themer-add-on/commit/25ec5759c52e85a96705abc12e3568b1de2be8e4
