### ISSUE TITLE
Show field label?

### ISSUE THREAD

**Issue by dollhousedigital** [pods-framework/pods-beaver-builder-themer-add-on#38]
I am looking to show the field label above any Pods fields added to Beaver Themer.

Is there any way to do this currently?

Cheers!

**Comment by quasel** [comment]
No currently not dynamically - would need some php code like:

``` php
echo $mypod->fields( 'your_field', 'label' ) 
```

do you need/expect your labels to change dynamically? If not you could just put them in plain text! 
what's your use case?

**Comment by dollhousedigital** [comment]
Heya, thanks for that. :-)

Yes, I am trying to add dynamic labels.

I am creating a directory site. I have custom post types that include many custom fields, such as:
Headline, Location, Phone, Contact, Email, Address, Info, Options etc.

If one of these fields is not needed for a specific entry I need the title to not show on the template, as I will be adding many custom field options for each category that will not be needed on all posts.

Trying to find the best solution.

**Comment by quasel** [comment]
Maybe this helps: http://kb.wpbeaverbuilder.com/article/462-hide-rows-or-modules-based-on-field-connections-themer

**Comment by dollhousedigital** [comment]
Ah yes!

That may be a much better way to approach this.
Would give me much more control of field titles and their styling. :-)

Thanks! Much appreciated!
