### ISSUE TITLE
field connections URL, add magic tag as option e.g  inside a button

### ISSUE THREAD

**Issue by flavioguzman** [pods-framework/pods-beaver-builder-themer-add-on#39]
Add a connection to insert magic tags inside a button.

![image](https://user-images.githubusercontent.com/30154431/28175637-2c203f4e-67cb-11e7-9eed-dd78e625c7ff.png)

**Comment by quasel** [comment]
good catch and great feedback! should be easy - you did become a friends of pods right?

**Comment by flavioguzman** [comment]
Yes I did!

**Comment by quasel** [comment]
revisiting this as part of the 1.2 release and thinking again about it why would you need the option? as you could just use the URL Field? I'm sure I'm missing something ^^

**Comment by rpaasch** [comment]
I have been pulling my hair out all night into I stumbled over this. I want my users to be able to pick out a pdf-file from the media library using the "File / Image / Video" [type: file]. Then I would need afterwards to place eg. the url of the pdf in a button... Does it make sense?

**Comment by quasel** [comment]
Did just answer in the slack chat - @flavioguzman, @rpaasch 
simplest solution until I find the time/idea hoot best tackle that:

just enter the `[pods]{@any_field}[/pods]` or for file/image stuff `[pods]{@file_field._src}[/pods]`into the field which expect's you to use link :D I'll add a magic tag option and maybe take a look if it's possible to add the link of files/image as url type which would be the cleanest solution!

**Comment by quasel** [comment]
added magic tags / templates as available option - although less fail safes ;) but with great power comes responsibility ;)
