### ISSUE TITLE
Not Working With Beaver Builder 2 Alpha 3

### ISSUE THREAD

**Issue by reachadam** [pods-framework/pods-beaver-builder-themer-add-on#41]
Tested in multiple websites to confirm the issues. 

<img width="598" alt="screenshot 2017-08-07 18 23 35" src="https://user-images.githubusercontent.com/20959226/29096940-0e882768-7c4c-11e7-8348-5ea146f0f7dd.png">

**Comment by quasel** [comment]
Thats because of: 

> Settings forms now load instantly! We've completely rewritten the settings forms in JavaScript so they don’t need to be loaded from the server anymore. The only time something needs to load is if you’re using a third party add-on that introduces legacy PHP fields. We’ll have docs on the new JavaScript settings APIs when 2.0 is released and hope that all major add-on authors will convert their fields to JavaScript so everything loads instantly!

seems I need to change the complete configuration creation - as it's now needed earlier!

**Comment by quasel** [comment]
this will be fixed with BB 2.0 Alpha 6 - they had to replace `function_exists` with `is_callable`

**Comment by reachadam** [comment]
So the new alpha was released today, but there are still some little bugs. When you go so see the list of field names to connect, they are all blank. https://www.dropbox.com/s/x5zfxpsovzh3hyp/Screenshot%202017-09-19%2011.45.31.png?dl=0

**Comment by quasel** [comment]
Fixed with BB 2.0 Alpha 6.1 - thanks for reporting it! Justin fixed it ;)
