### ISSUE TITLE
"Field from Settings / Current User" <option> showing empty/blank

### ISSUE THREAD

**Issue by rob** [pods-framework/pods-beaver-builder-themer-add-on#42]
The "Field from Settings / Current User" dropdown appears blank / empty because the HTML `<option>` tag doesn't have the value between it, e.g.:

_current_: `<option value="cptv_settings:inside_cptv_posts"></option>`
_should probably be_: `<option value="cptv_settings:inside_cptv_posts">inside_cptv_posts</option>`

Running Beaver Plugin 2.0-alpha3.

![screen shot 2017-08-08 at 6 16 18 pm](https://user-images.githubusercontent.com/503/29098301-c8815c14-7c6c-11e7-93ea-965140146f71.png)

![screen shot 2017-08-08 at 6 15 23 pm](https://user-images.githubusercontent.com/503/29098298-c3357948-7c6c-11e7-9880-f17ea4cb2487.png)

Everything still works, though.

**Comment by quasel** [comment]
Thank's will look into it seems related to #41 - hope I can take a look this week!

**Comment by quasel** [comment]
Okay can reproduce it, sadly there is no documentation yet what they change seems I need to dig into the code and see what has been changed :/

**Comment by quasel** [comment]
Fixed with BB  2.0  Alpha 6.1 - thanks for reporting it!
