### ISSUE TITLE
Problem with PODS Beaver Themer add on 

### ISSUE THREAD

**Issue by RamonaMarie** [pods-framework/pods-beaver-builder-themer-add-on#45]
Updated Beaver Builder plugin this morning. Got problems with Posts Carousel. BB support uncovered this - https://www.screencast.com/t/bTDKyMBJh

I'm not sure what else you need. Let me know.
I have posted in the slack channel as well. Thanks.

**Comment by quasel** [comment]
I can't reproduce the error on my test installs
it seems it only happens on beaver themer templates on your page - either the installation is broken our it's an rare edge case :/

**Comment by quasel** [comment]
seems an isolated issue on your hosting - going to close that one - if you have new informations free feel to comment!
