### ISSUE TITLE
Running out of memory when trying to add pods template to accordion

### ISSUE THREAD

**Issue by dlfdlf56** [pods-framework/pods-beaver-builder-themer-add-on#49]
Running Wordpress 4.8.2 - Pods 2.6.11 and Pods Beaver Themer Add-on 1.1.1
This used to work but broke in one of the recent versions.  The same template works perfectly if put into a page without an accordion.  When I try to save a shortcode call to a pods template in an accordion, it hangs and then eventually runs out of memory and crashes.  Here is the error code:
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 383795200 bytes) in .../public_html/wp-includes/post-template.php on line 242

**Comment by quasel** [comment]
Which Version of BB are you using? If it worked what changed on your side? - For Pods/Integration it shouldn't matter where you put the Shortcode! Did you try clearing Cache - is there an error in the console log?

**Comment by dlfdlf56** [comment]
Running BB version 1.6.2.  Yes, I have cleared the cache, also tried remaking the template all to no avail.  The only thing that has changed are the plugin updates - the templates are the same ones that it used to work with.  Updates have come out for pods, BB and Pods Beaver Themer since it last worked.  Not sure about the console log.  Where would I find that-Google searches aren't turning up anything regarding that log?

**Comment by quasel** [comment]
Don't think it's related to the Pods integration as i can't reproduce it on my Test Site - did you contact BB Support? did you try other shortcodes? - regarding console - it's part of the dev tools of most of the browsers - https://www.wickedlysmart.com/hfjsconsole/
