### ISSUE TITLE
Fatal error: Allowed memory size -> never ending recursion

### ISSUE THREAD

**Issue by tsetzlerAC** [pods-framework/pods-beaver-builder-themer-add-on#51]
I installed Beaver Themer & Pods Beaver Themer Add-On, tried using this and I keep receiving the error:

"Fatal error: Allowed memory size of 671088640 bytes exhausted (tried to allocate 36864 bytes) in /home/forge/oxford.actualsize.me/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 654"

This is causing an issue disabling the beaver builder editor. Tried increasing the memory limit didn't work, Beaver Builder, Theamer & Pods Beaver Themer Add-On are all up to date.

**Comment by lmichd2d** [comment]
Hi There.. I am having the same issue. Has anyone fixed this issue?

[05-Nov-2017 07:19:29 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 16384 bytes) in /home/lucasm7/lmich.com/wp-content/plugins/pods-beaver-builder-themer-add-on-1.x/classes/class-pods-beaver-page-data.php on line 649

I have increased the memory limit in my wp-config.php to 256M but does not change the situation.

The environment to my website is:-
WordPress Version: 4.8.3
PHP Version: 7.0.22
MySQL Version: 5.6.35
Server Software: Apache
Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Session Max Lifetime: 1440
Currently Active Plugins:

Akismet Anti-Spam: 4.0
Beaver Builder Plugin (Standard Version): 2.0
Beaver Themer: 1.0.2.1
Coming Soon Page & Maintenance Mode by SeedProd: 5.0.14
Elementor: 1.7.12
Elementor Pro: 1.9.5
Enhanced Media Library: 2.4.5
GP Premium: 1.4.3
Imsanity: 2.3.9
iThemes Security: 6.6.1
MailChimp for WordPress: 4.1.9
Pods - Custom Content Types and Fields: 2.6.11
Pods Beaver Themer Add-On: 1.1.1
UpdraftPlus - Backup/Restore: 1.13.12
Yoast SEO: 5.6


Please, anyone, if you have solved this problem, kindly share with me what needs to be done. thank you.

**Comment by quasel** [comment]
Pleas test again with the new Version 1.1.2 either from GitHub or wait for the official wp.org release (hopefully today)

**Comment by quasel** [comment]
strange - that's now related to an BB Ajax call - hard to tell where that comes from without more information - does it happen on every page? what did you do?

**Comment by tsetzlerAC** [comment]
No, it only happens on the pages where you try and use the Pods Beaver Themer Add-On.

Example, my post types have relationships I'd like to show on my template with the page builder.  As soon as I add this it errors out and I receive the error above.

**Comment by quasel** [comment]
can you share a login? or provide more details about your setup like Template code used - does it happen if you just try to display one field? I can't reproduce the error on my testing site :/

**Comment by tsetzlerAC** [comment]
It only happens when you try and add anything to the template/post type.

Will send login info through slack.

**Comment by quasel** [comment]
Th issue is:

POD A  Bidirectional link to POD B Bidirectional Link to POD C 

recurse_pod_fields() is then stuck between POD B and POD C bouncing forever 
@sc0ttkclark any quick idea?

**Comment by quasel** [comment]
Problems:
- [ x] avoid recursion 
- [ x] allow visiting the same pod again  

Solved by keeping track of `current_pod.field_name` on the way down to avoid passing the same combination again, but removing the static approach to be able to go down again coming from a different field/pod ... 

I hope the image helps understand it ;) 
![recursion](https://user-images.githubusercontent.com/9464217/32550345-001ef74a-c48d-11e7-82f4-0df07c78ec73.png)
