### ISSUE TITLE
Error msg adding post content

### ISSUE THREAD

**Issue by socialspark** [pods-framework/pods-beaver-builder-themer-add-on#53]
Using:
Beaver Builder Theme: 1.6.2
Beaver Builder 2.0
Beaver Themer 1.0.2.1
Pods 2.6.11
Pods Beaver Themer add-on 1.1.1
PowerPack for Beaver Builder 1.4.0.2

Trying to add a new Post Content Grid and get an error is inside the grid box on the Content Tab, but not any of the other tabs. This happens for both the native BB posts module and the PowerPack posts module. The module appears to work, and displays the requested information, but the published page has even more errors at the bottom of the page, below the footer.

Error inside the module box, content tab (screenshot: https://www.screencast.com/t/9wasnhBfIS):
Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392

Error below the copyright footer after the page is published (screenshot: https://www.screencast.com/t/Z9EGYvT4p):
Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 391 Deprecated: Non-static method PodsBeaverPageData::recurse_pod_fields() should not be called statically in /app/public/wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 392 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-ui-settings-forms.php on line 153 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3401 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414 Notice: Undefined index: type in /app/public/wp-content/plugins/bb-plugin/classes/class-fl-builder-model.php on line 3414

**Comment by quasel** [comment]
Pleas use the Version from GitHub - https://github.com/pods-framework/pods-beaver-builder-themer-add-on/archive/1.x.zip - I will plan to release it to WP Repo in the next few days just not at home until Tuesday - sorry ! If the error still exists please post again in the issue!

**Comment by socialspark** [comment]
Thank you so much Bernhard! That fixed everything.

On November 4, 2017 at 4:52:40 PM, Bernhard (notifications@github.com)
wrote:

Pleas use the Version from GitHub -
https://github.com/pods-framework/pods-beaver-builder-themer-add-on/archive/1.x.zip
- I will plan to release it to WP Repo in the next few days just not at
home until Tuesday - sorry ! If the error still exists please post again in
the issue!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pods-framework/pods-beaver-builder-themer-add-on/issues/53#issuecomment-341929007>,
or mute the thread

**Comment by quasel** [comment]
Glad to hear!
