### ISSUE TITLE
No output from Beaver Builder posts module when pods_beaver_fake_loop_add_actions is active.

### ISSUE THREAD

**Issue by adoerler** [pods-framework/pods-beaver-builder-themer-add-on#55]
Hi,

you've implemented a workaround in #15 which seems to break the default Posts plugin of Beaver Builder.

I've the following setup:
* WordPress 4.8.3
* Beaver Builder 2.0.1.1
* Beaver Themer Add-On 1.0.3
* Pods 2.6.11
* Pods Beaver Themer Add-On 1.2.1

I've an custom post type created with Pods where I added a relation to add multiple images. They should be shown in the single view of this post.
So far so good: Thanks to this great plugin it is very easy to connect a gallery with the Pods gallery field.
The single view works like a charm.
Unfortunately we've seen, that the list view (Posts plugin) does not show anything but an empty div in the html:
```
<div class="fl-post-content clearfix" itemprop="text"></div>
```

After disabling the plugin the post show up in archive page, but naturally the gallery in single view has gone.

After digging further I've found out that the problem is within the `pods_beaver_fake_loop_add_actions`. i.e. `$wp_query->in_the_loop = false;` Removing this line or removing the whole action makes the posts appear again.

What makes me wondering:
In #15 there was the following code:
```
if ( is_pod() ) {
		// Stop faking being in the loop.
		$wp_query->in_the_loop = false;
	}
```

But in v1.2.1 the `is_pod()` is missing, see: https://github.com/pods-framework/pods-beaver-builder-themer-add-on/blob/1.x/pods-beaver-themer.php#L148

If I add the `is_pod` statement everything seems to work for me, but I've haven't used any Pods shortcodes for now.

Therefore my intermediate fix is to remove this fake action in my `functions.php`:
```
dd_action( 'fl_page_data_add_properties', 'gm_remove_action', 20);
function gm_remove_action() {
	remove_action( 'fl_builder_loop_before_query', 'pods_beaver_fake_loop_add_actions');
}
```

Can you tell me, why the `is_pod()` was removed in commit https://github.com/pods-framework/pods-beaver-builder-themer-add-on/commit/3092e2791de5b6a3502cbb253092c17f018213dd#diff-bc4047980660b5744123f02c157a67edL169 ?

The same is true for the `pods_beaver_fake_loop_true` function. The `is_pod()` was removed in the very same commit.

If there is anything else I can provide to help finding the root cause, please let me know.

Kind regards
Andreas

**Comment by quasel** [comment]
Does this only happen in list view for you or in other display settings too? Can you share a Link to your site? and maybe a login? As this works just fine on my test site!
Did you use any other Features? Pods auto Templates? Any Errors with WP_DEBUG True? Did you disable all other Plugins and used a default theme? 

If I remember correctly there were some minor issues with is_pod() and extended CPT,

**Comment by adoerler** [comment]
Hi,

thanks for your fast response and the hint with trying default theme.
Never thought that my Beaver Builder Child theme could have something to do with this.
Actually I've an filter to add some text to woocommerce products if a non-empty description is set.
This seems to be the root cause of the issue:
```
function empty_content($str) {
	return trim(str_replace('&nbsp;','',strip_tags($str))) == '';
}
function single_product_content() {
	$theContent = get_the_content();
	if ( is_product() ) {
		return (!empty_content($theContent) ? '<h3>Description</h3>'.$theContent : '');
	} else {
		return FLBuilder::render_content($theContent);
	}
}
add_filter( 'the_content', 'single_product_content' );
```
If I remove this filter, the posts are shown.
The problem is obviously that I've used `get_the_content()` again instead of just take the content passed to the filter.

Thanks for pointing me into the right direction!
Andreas

**Comment by quasel** [comment]
yep the_content can be tricky especially together with Beaver Themer but in your Code Example just use 
function single_product_content( $the_content ). to get the content as it's a filter ... but no idea about other ramifications of your function! 

Filter and Action in WordPress are a bit tricky to grasp sometimes :D - and Thank You for the Detailed Report!
