### ISSUE TITLE
get feature image from relationship field

### ISSUE THREAD

**Issue by smatzis** [pods-framework/pods-beaver-builder-themer-add-on#56]
Hello Bernhard. How are you doing?
Example: 2 pods: books and authors and bi-directional relationship field: books written. A book can only have one author.
When i am on a page of a book post, i would like to show the featured image of the related author. However i cannot find the correct code for this to work. Could you please help me out?
I have tried these shortcodes: 
```
[wpbb post:pods_display field='book_author.post_thumbnail.medium']
[wpbb post:pods_display field='book_author.post_thumbnail_url.medium']
[wpbb post:pods_display field='book_author.post_thumbnail._img.medium']
```
but nothing happens. Neither the image nor the url is shown. Same with magic tags.

For a workaround i have added a file field (called book_author_image) to the authors pod and have uploaded an image, which i can display using the following shortcode:
`[wpbb post:pods_display field='book_author.book_author_image._img.medium']`

Is it possible to tell me please what am i doing wrong and how to display the featured image?

So much thanks for your work!

**Comment by quasel** [comment]
Sorry I missed that - if it breaks with magic tags then I'm afraid  that's a Pods Issue @jimtrue did you encounter something like that? need to test it ;)

**Comment by quasel** [comment]
did some further Research just works for me - could it be that you configured your book pod to allow multiple authors? - closing this as it works for me!
