### ISSUE TITLE
Notice: Undefined index: file_uploader in /class-pods-beaver-page-data.php on line 585

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods-beaver-builder-themer-add-on#59]
`Notice: Undefined index: file_uploader in /wp-content/plugins/pods-beaver-builder-themer-add-on/classes/class-pods-beaver-page-data.php on line 593`

**Comment by quasel** [comment]
#60 Fixes the error msg but should in this case the field be added to the list of fields or not? For which type of field does that happen? - the configuration array is a beast :D and the same beast is this nasty function to get all fields that mach the field connection :D

**Comment by JoryHogeveen** [comment]
Haven't got the time to actually debug this, just found the notice and I always use `pods_v` for getting field/pod data since the huge config arrays aren't reliable.
