### ISSUE TITLE
Pods Data Content Source Makes Scrolling Arrows Disappear

### ISSUE THREAD

**Issue by expionage** [pods-framework/pods-beaver-builder-themer-add-on#61]
Hi guys,

Issue: I am using the UABB Posts Module by the Astra team in BB/Beaver Themer and while displaying the Post results in a Carousel format, the arrows allowing the user to scroll disappears.

http://screencast-o-matic.com/watch/cFVirMo1mE

This issue is related to the thread:
https://pods.io/forums/topic/pods-data-content-source-overwrites-posts-module/

From what I understand, they've mentioned that Pods is overwriting the HTML structure and removing their carousel arrow’s HTML.

For the full context, please see thread: https://pods.io/forums/topic/pods-data-content-source-overwrites-posts-module/

Please let me know if you have any questions.

Thanks!

**Comment by jimtrue** [comment]
Did you open support tickets with the UABB folks and can you reference the ticket above in that ticket (since that is a premium plugin) or in their forum post? It would be most helpful to get @quasel directly connected with their developer.

**Comment by expionage** [comment]
Sounds great, I've gone ahead and followed up with them with an update on the GH URL and ticket #.

**Comment by quasel** [comment]
Will take a look after the weekend I hope - but the integration doesn't change anything HTML related - and neither does Pods afaik, I just change the item's in the Query - does it work with a different pos carousel module? 

I have on idea although - in the end we filter just the query for the posts module but I needed to do special stuff for UABB so maybe there is an issue - but that's totally unrelated to what the UABB Team says - we don't do anything to the HTML in the integration and neither does Pods as far as I know ...

**Comment by expionage** [comment]
Great, thanks, @quasel! Please let me know if there's anything I can do on my end or if I can help re-test.

**Comment by quasel** [comment]
is this still an issue? Currently working on updating and scrubbing bugs ;)

**Comment by quasel** [comment]
Closing, if there is still an issue @expionage feel free to reply!

**Comment by quasel** [comment]
Did work in my Tests now - including arrows working on adding the Taxonomy filter with #71
