### ISSUE TITLE
Feature request:  Support display current author fields

### ISSUE THREAD

**Issue by beaverbuilder** [pods-framework/pods-beaver-builder-themer-add-on#63]
This came up in a BB support ticket.  The user field does not work to show a current author's fields on an author archive, for example.

**Comment by quasel** [comment]
I'll take a look!

Current workaround for most of the field's if I remember it correctly  from our chat -> Beaver Themer author meta

**Comment by beaverbuilder** [comment]
-- Please reply above this line --

Thanks for contacting Beaver Builder support! We've received your
message and want you to know we're on top of it! 

We try our best to respond same day, otherwise, you can expect a
response by the next business day. Support is unavailable on weekends
and US holidays.

While you're waiting, please feel free to check out our KNOWLEDGE
BASE [1] which includes installation walkthroughs, troubleshooting
guides, FAQs, and more! We also have a great SUBREDDIT FORUM
[2], Vimeo [3] and YOUTUBE [4] channels!

Did you know we have a thriving community ready to help and chat
anything Beaver Builder related? Check out our FACEBOOK GROUP [5],
or Slack group [6], if that's more your thing.

If you end up finding the answer you were looking for, or, solving an
issue on your own, please reply directly back to this email to keep us
updated. You do not need to resubmit a new ticket.

We look forward to helping you, and have a great day!


Links:
------
[1] https://kb.wpbeaverbuilder.com/
[2] /HTTPS://WWW.REDDIT.COM/R/BEAVERBUILDER/
[3] https://vimeo.com/beaverbuilder
[4] https://www.youtube.com/channel/UCvvtiNDweAHU-0mBeN1hh6A
[5] https://www.facebook.com/groups/beaverbuilders/
[6] https://beaverbuilders.herokuapp.com/
