### ISSUE TITLE
Feature request: Support display current author fields

### ISSUE THREAD

**Issue by codente** [pods-framework/pods-beaver-builder-themer-add-on#64]
This came up in a BB support ticket. The user field does not work to show a current author's fields on an author archive, for example.

**Comment by quasel** [comment]
I'll take a look!

Current workaround for most of the field's if I remember it correctly from our chat -> Beaver Themer author meta

**Comment by quasel** [comment]
Started working on it - feel free to test :D #79

**Comment by quasel** [comment]
- [ x ] string/html/.. connections
- [ ] image/s connection
- [ ] url connection
