### ISSUE TITLE
Title in Plugin Listing doesn't show Pods in the title

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-beaver-builder-themer-add-on#65]
This was reported from this Support Topic:
https://wordpress.org/support/topic/suggestion-rename-what-shows-in-wp-plugins-when-installed/

And here's an example of what is displayed in the Plugin List:
<img width="548" alt="image 2018-03-04 at 10 31 22 am" src="https://user-images.githubusercontent.com/3052875/36948436-bea26852-1fa8-11e8-8f07-ba94fd0a74b0.png">

Not quite sure why this doesn't show the actual name of the plugin from the WordPress.org Respository.

**Comment by quasel** [comment]
This happens when using a non-english admin language due to a bug in Beaver Themer and is not related to pods - Beaver Themer has the same issue (there is supposed to be a different string too - see english version)

**Comment by jimtrue** [comment]
What is the actual solution?? @quasel

**Comment by jimtrue** [comment]
Can you link to a bug report with Beaver Themer??
