### ISSUE TITLE
WYSIWYG text formatting stripped out when using a relationship

### ISSUE THREAD

**Issue by expionage** [pods-framework/pods-beaver-builder-themer-add-on#66]
Hi guys,

Came across this issue while trying to dynamically generate a page from content across different CPTs. Here are the observations:

1.) I have two Themer layouts and two CPTs

2.) Layout #1 - I have a WYSIWYG text module for CPT #1  that connects to a field in CPT #2

3.) When it pulls back the data in that field, all of the formattings (e.g. line breaks) is stripped out

4.) Layout #2 - A test layout was created and applied only to CPT #2 as a way to see what happens when you connect and display that field without linking to another CPT -- in this instance, the formatting (line breaks) displayed just fine

GIF comparing the two: https://cl.ly/3A0p073T1q0w

Please let me know if you have any questions.

**Comment by quasel** [comment]
is this still an issue? - can you share the more detailed what you did in step 2?  As a Tip use an HTML Module if layout seems weird - depends on how you did "connect" the fields ...

**Comment by quasel** [comment]
closing until further feedback - once again sorry @expionage for my late reply's was a busy time for important stuff you can find me on the Pods Slack - https://pods.io/forums/chat/
