### ISSUE TITLE
Linking with multiple of a CPT and using their featured images in a slider

### ISSUE THREAD

**Issue by GregorR1** [pods-framework/pods-beaver-builder-themer-add-on#77]
## Issue Overview
Trying to use featured image of multiple CPT posts to create a row background slideshow with beaver builder.  Made the relationship and selected the custom posts to link and set up the row background slideshow.  The issue is that the images aren't showing up.

## Expected Behavior
Featured images of CPT's should be showing as a slideshow in page header.

## Current Behavior
The images are not showing in my page header. 

If I create a new image field in my CPT and link it with "rel_gallery_featured_images.gallery_slider_image" then it works fine.

## Steps to Reproduce (for bugs)

1. Relationship set up between page and multiple of the CPT "gallery"
2. Page header set up as "Slideshow" and linked to "gallery" posts with advanced > "rel_gallery_featured_images.post_thumbnail"
3. Images not showing

## Pods Package Export (helpful!)
{"meta":{"version":"2.7.6","build":1531321591},"pods":{"2044":{"id":2044,"name":"gallery","label":"Galleries","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"image_gallery":{"id":2045,"name":"image_gallery","label":"Image Gallery","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"gallery_slider_image":{"id":2342,"name":"gallery_slider_image","label":"Gallery slider image","description":"","help":"","class":"","type":"file","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"Gallery","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"gallery","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_attachment_category":"0","built_in_taxonomies_attachment_tag":"0","built_in_taxonomies_category":"0","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-images-alt2","menu_position":"4","supports_jetpack_publicize":"0","supports_jetpack_markdown":"0","built_in_taxonomies_product_cat":"0","built_in_taxonomies_product_shipping_class":"0","built_in_taxonomies_product_tag":"0","built_in_taxonomies_product_type":"0","built_in_taxonomies_product_visibility":"0"},"2331":{"id":2331,"name":"page","label":"Page","description":"","type":"post_type","storage":"meta","object":"page","alias":"","fields":{"rel_gallery_featured_images":{"id":2332,"name":"rel_gallery_featured_images","label":"REL gallery Featured Images","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"gallery","sister_id":"","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"rel_category_featured_images_copy":{"id":2349,"name":"rel_category_featured_images_copy","label":"REL category Featured Images (Copy)","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"taxonomy","pick_val":"product_cat","sister_id":"","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

## Related Issues and/or PRs
<!-- List related issues or PRs against other branches:  -->

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by quasel** [comment]
As discussed thats a bug from pods itself! Please add your comments there - https://github.com/pods-framework/pods/issues/3779
