### ISSUE TITLE
Suggestion: Relationship Fields

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-beaver-builder-themer-add-on#8]
Maybe it automatically ports related records into a 'posts list' or 'posts gallery' object?
http://kb.wpbeaverbuilder.com/article/67-posts-posts-carousel-and-posts-slider-modules-overview

The biggest part would be the ability to pass over a filter for the related posts.

**Comment by quasel** [comment]
If BB theme doesn't add a field_connection for it maybe add a "Setting"
Starting Point FLBuilderLoop::query( $settings ); 
Action:  fl_builder_loop_before_query
Filter: fl_builder_loop_query or fl_builder_loop_query_args

**Comment by quasel** [comment]
example https://www.framethe.me/getting-meta_query-working-with-post-module/

**Comment by quasel** [comment]
done - thanks do the new filters from BB Team - see posts module, it respects the Order By, etc from the default fields!

**Comment by quasel** [comment]
working on it see #28
