### ISSUE TITLE
Connection for maps

### ISSUE THREAD

**Issue by 3001Web** [pods-framework/pods-beaver-builder-themer-add-on#85]
## Issue Overview
We collect venue address for single post and would like to feed that to the maps module in beaver which simply asks for an address. Currently no way to connect them

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by quasel** [comment]
See - https://wordpress.org/support/topic/no-support-for-map/ - will update there!

**Comment by quasel** [comment]
Okay was an missunderstanding - and a other Pluign interfering with Field connections!
