### ISSUE TITLE
PodsDFV is not defined with Media extended

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods-beaver-builder-themer-add-on#98]
See - https://github.com/pods-framework/pods/pull/5314#issuecomment-474074347 

some ideas… research a better way? 

```
// Enable DFV editing on Frontend
add_filter( 'pods_enqueue_dfv_on_front', '__return_true');
```

```
// Enable DFV editing on Frontend for Beaver Builder Only
if ( isset($_GET['fl_builder']) ) {
  add_filter( 'pods_enqueue_dfv_on_front', '__return_true');
}
```

**Comment by tannerchung** [comment]
This doesn't seem to work with Elementor. I've tried adding https://github.com/pods-framework/pods/pull/5314 manually to the `PodsInit.php` file and the `functions.php` file but I'm still having no luck: https://github.com/pods-framework/pods/pull/5314

**Comment by quasel** [comment]
Hi @tannerchung - the patch will be part of the 2.7.13 release for pods, until then you would need to load the code from - https://github.com/pods-framework/pods/tree/feature/5313-enqueue-dfv-frontend - to test it!

**Comment by quasel** [comment]
part of pods core - https://github.com/pods-framework/pods/releases/tag/2.7.23 for Beaver Builder see details  https://github.com/pods-framework/pods/issues/5799 

 if you need it for other builders see more details -> https://github.com/pods-framework/pods/issues/5864
