### ISSUE TITLE
Nickname showing Username

### ISSUE THREAD

**Issue by AwesomeWebDesigns** [pods-framework/pods-beaver-builder-themer-add-on#99]
## Issue Overview

Hi! I am connecting the author nickname to my posts with Pods and Beaver Themer. When adding the code for the nickname, it just shows the username.

This is the code I am adding: [wpbb post:author_name type=‘nickname’ link=‘no’]

## Expected Behavior

The result should be the nickname, not the username of the author.

**Comment by quasel** [comment]
Hi that's a field connection from BB and has nothing todo with pods! 

*For General Beaver Builder Support*: Use https://beaverbuilders.herokuapp.com/ or https://www.wpbeaverbuilder.com/beaver-builder-support/ or ask in the FaceBook Group - we are a very small team at Pods and need to focus our time on our plugin. We only support direct integration with Beaver Themer and our Beaver Themer Addon here.  *Remember, you pay for premium support from the Beaver Builder Team with your license.* Always work the problem with them _first_ before bringing the question here. We want to be helpful, but we also want to make sure you get the best support possible. Thanks!
